In [15]:
import torch
import torch.nn as nn

In [2]:
w = torch.tensor((1,2))

In [3]:
w.shape

torch.Size([2])

In [4]:
w

tensor([1, 2])

In [5]:
w1 = torch.empty((1, 2))
w1.shape

torch.Size([1, 2])

In [6]:
w1

tensor([[0., 0.]])

In [12]:
b = torch.tensor(3)
print(b)
b.shape

tensor(3)


torch.Size([])

In [14]:
b1 = torch.empty(2)
b1

tensor([2.8026e-45, 0.0000e+00])

In [19]:
nn.init.uniform_(b1)

tensor([0.8406, 0.0451])